version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: whatsway-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatsway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  whatsway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsway-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/whatsway
      
      # Session
      SESSION_SECRET: ${SESSION_SECRET:-change-this-secret-in-production}
      
      # WhatsApp API
      WHATSAPP_BUSINESS_ACCOUNT_ID: ${WHATSAPP_BUSINESS_ACCOUNT_ID}
      WHATSAPP_ACCESS_TOKEN: ${WHATSAPP_ACCESS_TOKEN}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WEBHOOK_VERIFY_TOKEN: ${WEBHOOK_VERIFY_TOKEN}
      WHATSAPP_API_VERSION: ${WHATSAPP_API_VERSION:-v23.0}
      
      # MM Lite API (Optional)
      MM_LITE_API_URL: ${MM_LITE_API_URL:-}
      MM_LITE_API_KEY: ${MM_LITE_API_KEY:-}
      
      # Application
      APP_URL: ${APP_URL:-http://localhost:5173}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:5173}
      
      # Rate Limiting
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-60000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-info}
      
      # Node Environment
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "5173:5173"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: whatsway-nginx
    profiles: ["production"]
    depends_on:
      - whatsway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped

volumes:
  postgres_data: