version: "3.9"
services:
  app:
    build: .
    container_name: whatsway-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: whatsway-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: whatsway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
