version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: whatsway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - whatsway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: whatsway-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT:-5001}:5001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-changeme}@db:5432/whatsway
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - whatsway-network
    volumes:
      - ./uploads:/app/uploads  # For file uploads if needed

volumes:
  postgres_data:
    driver: local

networks:
  whatsway-network:
    driver: bridge
    